language: cpp

matrix:
  include:
    # windows msvc
    - name: "Windows / MSVC"
      os: windows
      script:
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && build_msvc.bat'
        - build/example_basic_msvc.exe
        - build/example_suite_msvc.exe
        - build/example_cpp_msvc.exe

    # windows clang
    - name: "Windows / Clang"
      os: windows
      compiler: clang
      before_script: chmod +x build_clang_gcc.sh
      script: ./build_clang_gcc.sh
      after_success:
        - build/example_basic_clang.exe
        - build/example_suite_clang.exe
        - build/example_cpp_clang.exe

    # windows gcc
    - name: "Windows / GCC"
      os: windows
      compiler: gcc
      before_script: chmod +x build_clang_gcc.sh
      script: ./build_clang_gcc.sh
      after_success:
        - build/example_basic_gcc.exe
        - build/example_suite_gcc.exe
        - build/example_cpp_gcc.exe

    # linux clang
    - name: "Linux / Clang"
      os: linux
      compiler: clang
      before_script: chmod +x build_clang_gcc.sh
      script: ./build_clang_gcc.sh
      after_success:
        - build/example_basic_clang.exe
        - build/example_suite_clang.exe
        - build/example_cpp_clang.exe

    # linux gcc
    - name: "Linux / GCC"
      os: linux
      compiler: gcc
      before_script: chmod +x build_clang_gcc.sh
      script: ./build_clang_gcc.sh
      after_success:
        - build/example_basic_gcc.exe
        - build/example_suite_gcc.exe
        - build/example_cpp_gcc.exe

    # macOS C
    - name: "macOS"
      os: osx
      osx_image: xcode10.1
      compiler: clang
      before_script: chmod +x build_clang_gcc.sh
      script: ./build_clang_gcc.sh
      after_success:
        - build/example_basic_clang.exe
        - build/example_suite_clang.exe
        - build/example_cpp_clang.exe