matrix:
  include:
    # win64 msvc C
    - name: "Win64 / MSVC / C"
      os: windows
      script:
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && build_msvc.bat'
        - build/example_basic_msvc.exe
        - build/example_suite_msvc.exe

    # win64 msvc C++
    - name: "Win64 / MSVC / C"
      os: windows
      script:
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && build_msvc.bat'
        - build/example_cpp_msvc.exe

    # win64 clang
    - name: "Win64 / Clang / C"
      os: windows
      compiler: clang
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_basic_clang.exe
        - build/example_suite_clang.exe

    # win64 clang++
    - name: "Win64 / Clang / C++"
      os: windows
      compiler: clang++
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_cpp_clang.exe

    # windows gcc
    - name: "Windows / GCC / C"
      os: windows
      compiler: gcc
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_basic_gcc.exe
        - build/example_suite_gcc.exe

    # windows g++
    - name: "Windows / GCC / C++"
      os: windows
      compiler: g++
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_cpp_gcc.exe

    # linux clang
    - name: "Linux / Clang / C"
      os: linux
      compiler: clang
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_basic_clang.exe
        - build/example_suite_clang.exe

    # linux clang++
    - name: "Linux / Clang / C++"
      os: linux
      compiler: clang++
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_cpp_clang.exe

    # linux gcc C
    - name: "Linux / GCC / C"
      os: linux
      compiler: gcc
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_basic_gcc.exe
        - build/example_suite_gcc.exe
        - build/example_cpp_gcc.exe

    # linux g++
    - name: "Linux / GCC / C++"
      os: linux
      compiler: gcc
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_cpp_g++.exe

    # macOS C
    - name: "macOS / C"
      os: osx
      osx_image: xcode10.1
      compiler: clang
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_basic_clang.exe
        - build/example_suite_clang.exe

    # macOS C++
    - name: "macOS / C++"
      os: osx
      osx_image: xcode10.1
      compiler: clang++
      before_script: chmod +x build.sh
      script: ./build.sh $CC
      after_success:
        - build/example_cpp_clang.exe